### ISSUE TITLE
How about using a localization platform?

### ISSUE THREAD

**Issue by yarons** [ReallyGood/phpBB-Hebrew#59]
There are numerous localization platform such as Crowdin, Transifex, Weblate, TranslateWiki, etc.

Instead of translating manually using a localization platform will increase teamwork and will be easier to manage.

I'm pretty experienced with most of these platforms if you need any assistance.

**Comment by ShaharTal** [comment]
Good idea, applied to Crowdin's open-source license. Will keep you posted.

https://crowdin.com/project/phpbb-hebrew

**Comment by ShaharTal** [comment]
We are approved.

**Comment by yarons** [comment]
This is awesome! Yet there's a small misconfiguration, Hebrew is not the source language, it's the destination language so we need to add the English translation to the repository as a source (or use another Git as source) and add the configured git as translated material.

You can also ask the support guys, they are very fast and friendly.

**Comment by ShaharTal** [comment]
Our source language is set correctly to english, actually. But we do need the new english strings combined with what we're already happy with.

**Comment by yarons** [comment]
It is but if you'll look at the strings for translation you'll see that although it was configured to English the source is actually Hebrew because the source strings are read from the repository and this repository doesn't include the English original files :)

**Comment by ShaharTal** [comment]
I see. What is the "proper" flow then, having the english files in our repo as well? connecting another repo? (do you want to set it up? :))

**Comment by yarons** [comment]
LOL
The proper way is to configure the source strings and the localized strings location.

I will do it happily, I just have to make sure it's possible using the Crowdin support.

**Comment by ShaharTal** [comment]
I'm pretty sure I got those set properly, but I'll double check. Let's take this chat somewhere more private?
